version: '3'
services:
  cargodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.stage.dev
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - cargodb

volumes:
  mongodb_data_container:
